### ISSUE TITLE
Instructions on setting up env

### ISSUE THREAD

**Issue by Dannyzen** [iamnickvolpe/view#1]
I'd like to develop on view! It would help me get started faster if I had definitions and instructions regarding each `env` variable in the `.env-example` file. Specifically: 
1. What app APIs do I need secrets for? 
2. What is the Google Client ID? I am confused that the variable is titled "id" but the value is a url
3. What are FBS_\* variables? Where can I obtain them?

Thanks! 🍻

**Comment by iamnickvolpe** [comment]
Hey Danny! I just added a full walkthrough to the Readme that should answer your questions. Please go through it and let me know if you hit any snags.
https://github.com/iamnickvolpe/view/blob/master/README.md

To answer your specific questions:
1. You'll need secrets for a Google Cloud and Firebase project.
2. Google Client ID is the ID of the project you'll need to create
3. FBS stands for Firebase Service and you can obtain them once you create a Firebase project.
